### ISSUE TITLE
RFE: Add support for multiple versions of the same package

### ISSUE THREAD

**Issue by da-x** [juhp/cabal-rpm#11]
Cabal as standalone supports this. While RPM allows it to some degree, YUM and its later incarnation  DNF need too be aware of this too.

There's a discussion about it here: https://www.reddit.com/r/haskell/comments/2fynul/cabalrpm_does_recursive_packagingbuilding_and_yum/

This is helpful too:
http://www.rpm.org/wiki/PackagerDocs/MultipleVersions

**Comment by juhp** [comment]
I think with the advent of Stackage and LTS this is probably not needed.
Anyway I honestly doubt if I will find any time to work on this.
I guess dnf probably doesn't handle it any better than yum?

**Comment by da-x** [comment]
I agree. We can keep this as it is and utilize over Stackage and LTS instead.

BTW, I've been doing related work on this matter, named [stackage-dist](https://copr.fedorainfracloud.org/coprs/alonid/stackage-dist/) ([related post](https://groups.google.com/d/msg/haskell-stack/tYVXA4gVmEM/eWuuDqwRCQAJ)), and I have plans to take it to the next level - perform a binary distribution of a whole Stackage LTS. This will reduce the build times of [Fancydiff](https://copr.fedorainfracloud.org/coprs/alonid/fancydiff/build/157279/) on Copr from 15 minutes to 1 minutes. The interesting bits would be generating a single spec file that would result in a thousand or more of binary packages for each of the Haskell packages in LTS, and teach Stack to invoke 'dnf' or 'yum' to install them instead of building them in the home dir (.eg. `stack install-dist-deps`).
