### ISSUE TITLE
[RFE] add support for CBLRPM_DIFF envvar

### ISSUE THREAD

**Issue by mathstuf** [juhp/cabal-rpm#15]
It would be nice to use a difftool to view differences for a spec file.

**Comment by juhp** [comment]
Is there some standard envvar for this sort of thing (like `EDITOR`)?

**Comment by mathstuf** [comment]
Not to my knowledge. There's `git-difftool(1)` which has some information about how git decides this information.

**Comment by juhp** [comment]
Maybe there could be some envvar like `CBLRPM_DIFF` to allow this.
Not sure I will have much time for this soon though.

**Comment by mathstuf** [comment]
That sounds like a good solution.

**Comment by juhp** [comment]
I added CBLRPM_DIFF support.
