### ISSUE TITLE
`cabal-rpm spec` should error out / ask user when (Build)Requires is behind a conditional

### ISSUE THREAD

**Issue by yaccz** [juhp/cabal-rpm#17]
`cabal-rpm spec` should blow up / ask user when (Build)Requires is behind a conditional

example: `cabal-rpm spec transformers-compat` will depend just on transformers.

However, I'm building against ghc 7.8.3 so that's not optimal.

I'd like to have a configuration option (xdg config) for cabal-rpm to say to always either error out or ask me which of the conditionals to use if possible.

**Comment by juhp** [comment]
Okay I read this at the time but didn't fully understand what behaviour you want.
Sorry for not commenting before...

So you mean you want cblrpm to detect conditional depends in the .cabal file and ask what to do?
Or can you explain the use-case better?

**Comment by yaccz** [comment]
Some packages like transformers-compat are buildable with multiple GHC versions but by default only with ghc-7.10 (for example).

But since we did not yet have 7.10 on opensuse, the spec files generated by cabal-rpm needed manual intervetion to build with our ghc 7.8.

The problem with this was that I found out only after I tried to build the rpm package. I'd like cabal-rpm to inform me there are flags affecting build and dependencies so I know to check them even before attempting build.

**Comment by juhp** [comment]
I can "reproduce" but it looks to me like a "transformer-compat" bug to be honest.
AFAIK "manual: True" forces the flag to be static so looks like current transformers-compat-0.4.0.4 forces transformers-0.4 BICBW. I think I may open a bug on this.

Do you have any other examples?

**Comment by yaccz** [comment]
I remember hitting this with several packages but it's been a while and I don't remember now.

**Comment by juhp** [comment]
Well it is true that cabal-rpm does not do dependency version checking
(yet): that is certainly desirable.

**Comment by juhp** [comment]
Probably I would turn this into an RFE for cabal-rpm to check version constraints.

**Comment by juhp** [comment]
More recently I found out that there are actually multiple releases of transformers-compat etc:

eg https://hackage.haskell.org/package/transformers-compat-0.5.1.3 for ghc-7.8
and https://hackage.haskell.org/package/transformers-compat-0.5.1.4 for ghc-7.10+

Yeah it is a bit ugly but apparently that is the sanest approach.

**Comment by juhp** [comment]
Anything more here?

I am tempted to close this since I don't really know what to do.

**Comment by yaccz** [comment]
I don't know either anymore. I haven't touched haskell or rpm in a long time now.
