### ISSUE TITLE
mktemp: illegal option -- -

### ISSUE THREAD

**Issue by jagatsingh** [juhp/cabal-rpm#21]
$ cblrpm rpm hadoop-tools
mktemp: illegal option -- -
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix 
cblrpm: readProcess: mktemp "-d" "--tmpdir" "cblrpm.XXXXXXXXXX" (exit 1): failed

**Comment by juhp** [comment]
Which OS?  
What does `mktemp --version` say?
(Are you using GNU coreutils?)

**Comment by juhp** [comment]
Maybe an absolute path could replace `--tmpdir`, but still curious if you really need cblrpm on a non-GNU/Linux system?

**Comment by juhp** [comment]
Sorry going to close this for lack of information
