### ISSUE TITLE
[RFE] make cblrpm update command distro agnostic

### ISSUE THREAD

**Issue by mimi1vx** [juhp/cabal-rpm#25]
'cblrpm update' should be distro agnostic and only update spec Version + dependencies

**Comment by juhp** [comment]
Sorry could you explain what you don't want it to do?

**Comment by mimi1vx** [comment]
on suse distros:
now: 
    # cblrpm spec aeson-extra-0.3.0.0

create spec ghc-aeson-extra 

    # cblrpm update 
    grep: .git/config: No such file or directory
    patching file ghc-aeson-extra.spec
    cblrpm: user error (rpmdev-bumpspec: command not found)

diff old and new spec:

> diff --git a/ghc-aeson-extra.spec b/ghc-aeson-extra.spec.new
> index 966d9ca..c13f87a 100644
> --- a/ghc-aeson-extra.spec
> +++ b/ghc-aeson-extra.spec.new
> @@ -20,8 +20,8 @@
>  %bcond_with tests
>  
>  Name:           ghc-%{pkg_name}
> -Version:        0.3.0.0
> -Release:        0
> +Version:        0.3.1.0
> +Release:        0%{?dist}
>  Summary:        Extra goodies for aeson
>  Group:          System/Libraries
>  
> @@ -41,11 +41,13 @@ BuildRequires:  ghc-containers-devel
>  BuildRequires:  ghc-exceptions-devel
>  BuildRequires:  ghc-hashable-devel
>  BuildRequires:  ghc-parsec-devel
> +BuildRequires:  ghc-recursion-schemes-devel
>  BuildRequires:  ghc-scientific-devel
>  BuildRequires:  ghc-template-haskell-devel
>  BuildRequires:  ghc-text-devel
>  BuildRequires:  ghc-time-devel
>  BuildRequires:  ghc-time-parsers-devel
> +BuildRequires:  ghc-transformers-devel
>  BuildRequires:  ghc-unordered-containers-devel
>  BuildRequires:  ghc-vector-devel
>  %if %{with tests}
> @@ -53,6 +55,7 @@ BuildRequires:  ghc-quickcheck-instances-devel
>  BuildRequires:  ghc-tasty-devel
>  BuildRequires:  ghc-tasty-hunit-devel
>  BuildRequires:  ghc-tasty-quickcheck-devel
> +BuildRequires:  ghc-these-devel
>  %endif
>  # End cabal-rpm deps
>  
>

**Comment by juhp** [comment]
191e034 should fix the grep warning.

You don't have rpmdevtools in Suse?  (that's where `rpmdev-bumpspec` comes from)  Or any equivalent tool?  (I know I should really implement it in Haskell, but being lazy...)

I am not sure yet why `%{?dist}` is appearing there, strange.

**Comment by mimi1vx** [comment]
rpmdevtools , no , we have OBS:)  and we  haven't packages in git:)

better name for my RFE is  `cblrpm specupdate`  command:)

**Comment by juhp** [comment]
Ah yes, I think 0d34084 should fix the `%{?dist}` issue.

rpmdevtools is a collection of useful RPM cli tools.

```
$ rpmdev-bumpspec --help
Usage: rpmdev-bumpspec [OPTION]... SPECFILE...

rpmdev-bumpspec bumps release tags in specfiles.

Options:
  -h, --help            show this help message and exit
  -c COMMENT, --comment=COMMENT
                        changelog comment (default: "- rebuilt")
  -u USERSTRING, --userstring=USERSTRING
                        user name+email string (default: output from rpmdev-
                        packager(1))
  -r, --rightmost       bump trailing .<DIGIT> component if found, append .1
                        if not; no-op if -s is specified
  -s STRING, --string=STRING
                        bump trailing .STRING<DIGIT> component if found,
                        append .STRING1 if not; trumps -r
  -n NEW, --new=NEW     set new version and reset/set release (simple spec
                        files only)
  -V, --verbose         more output
  -v, --version         output version number and exit
```

Could you please open a separate ticket for "update package-version"?
It is something I would like to support (though Stackage support may help) but needs some work.

**Comment by juhp** [comment]
b368a52 should prevent using rpmdev-bumpspec on SUSE.
Can you try again and close if things are better now?

**Comment by juhp** [comment]
Did you have a chance to test?

**Comment by mimi1vx** [comment]
works good:) thanks
