### ISSUE TITLE
cabal update leaves tmpdirs behind

### ISSUE THREAD

**Issue by juhp** [juhp/cabal-rpm#26]
I think the problem is the `update` function in `Update.hs`.
There may be some other commands with this problem too.

**Comment by mimi1vx** [comment]
`cabal-rpm spec` same problem

**Comment by juhp** [comment]
> cabal-rpm spec same problem 

Can you describe how to reproduce that?

**Comment by mimi1vx** [comment]
i ran cabal-rpm spec in loop over full stackage list :) ..

and in /tmp/$USER/ is many folders cblrpm.{random} folders ... almost all empty

( https://github.com/mimi1vx/scripts/blob/master/st2obs/st2obs )

**Comment by juhp** [comment]
Okay thanks - I was hoping maybe you could give me a one line invocation that would cause a tmpdir to remain.  It seems only to happen in some cases.

**Comment by juhp** [comment]
Can you give of an example of a package for which this happens?

**Comment by juhp** [comment]
Okay I think I may have fixed this.
