### ISSUE TITLE
autopatch for hackage revisions

### ISSUE THREAD

**Issue by juhp** [juhp/cabal-rpm#30]
Sometimes a newer revision of a .cabal is available on Hackage, it would be better for cabal-rpm to include such revision updates automatically as a patch.  eg to build current mtl-2.2.1 for ghc8.

**Comment by mimi1vx** [comment]
or automatic use of "cabal-tweak-dep-ver" script in %setup section ?

**Comment by juhp** [comment]
Good idea - though that requires more parsing.
