### ISSUE TITLE
RFE: cabal-rpm should detect os from /etc/os-release

### ISSUE THREAD

**Issue by mimi1vx** [juhp/cabal-rpm#31]

**Comment by juhp** [comment]
Could you attach an os-release from SUSE?

**Comment by mimi1vx** [comment]
[os-release.tar.gz](https://github.com/juhp/cabal-rpm/files/336492/os-release.tar.gz)

os-release files for Tumbleweed, SLE12Spx and Leap

**Comment by juhp** [comment]
Thanks.  It looks like ID is the best thing to look at.

**Comment by mimi1vx** [comment]
possibility is also `rpm --eval '%{suse_version}'`

**Comment by juhp** [comment]
So using `%{suse_version}` would be better than `/etc/os-release` for now?

**Comment by mimi1vx** [comment]
it will be consistent with `rpm --eval` used for RH / Fedora detection

**Comment by juhp** [comment]
Okay, could you check if this works okay?

**Comment by mimi1vx** [comment]
works without any problem :+1:

**Comment by juhp** [comment]
Good, thanks :-)
