### ISSUE TITLE
RFE: cabal-rpm should have argument to set needed DISTRO

### ISSUE THREAD

**Issue by mimi1vx** [juhp/cabal-rpm#32]
for example `cblrpm spec -d redhat foo-0.0.1`
`cblrpm spec -d suse foo-0.0.1`

**Comment by juhp** [comment]
I agree this makes sense.

**Comment by mimi1vx** [comment]
https://github.com/juhp/cabal-rpm/pull/40

**Comment by peti** [comment]
Implemented in https://github.com/juhp/cabal-rpm/pull/40. I suppose this issue can be closed.
