### ISSUE TITLE
RFE: cabal-rpm should package documentation

### ISSUE THREAD

**Issue by hramrach** [juhp/cabal-rpm#47]
To build packages which installs documentation I have to patch cabal-rpm generated spec like this

@@ -125,6 +125,8 @@
 %files -f %{name}.files
 %defattr(-,root,root,-)
 %doc LICENSE
+%docdir /usr/share/%{pkg_name}-%{version}
+/usr/share/%{pkg_name}-%{version}

because otherwise the build fails.

Since the change is generic and independent of the actual package it can be generated by cabal-rpm to start with. Also cabal can generate those few lines in the most correct and canonical way.

Sure, some packages have documentation and some not. However, it is easier to delete pre-generated spec lines than it is to add them.

Also I think it preferable to support documented packages out of the box and require manual intervention on undocumented packages rather than the other way around.

**Comment by peti** [comment]
@hramrach, which package are you referring to, specifically?

**Comment by hramrach** [comment]
This is the one on which I tested frobbing the doc dir until it built
https://build.opensuse.org/package/rdiff/home:michals:haskell/text-zipper?linkrev=base&rev=4
These also needed the extra doc handling
https://build.opensuse.org/package/rdiff/home:michals:haskell/vty?linkrev=base&rev=2
https://build.opensuse.org/package/rdiff/home:michals:haskell/brick?linkrev=base&rev=3

**Comment by peti** [comment]
I am sorry, but I don't see how that change would have any meaning. You simply modified the %files pattern to match the directory instead of its contents, but why would you want to do that? Note that `text-zipper` compiles just fine without that modification: <https://build.opensuse.org/package/show/devel:languages:haskell:lts:next/ghc-text-zipper>.

**Comment by juhp** [comment]
I am not sure either exactly what you're seeing.  It would help if you could mention the environment (OS), cabal-rpm version (git tag) you're using, and provide rpmbuild error output.

**Comment by hramrach** [comment]
likely version

openSUSE:Factory                  cabal-rpm  0.10.0  15

build error with unpatched spec file
https://build.opensuse.org/package/live_build_log/home:michals:haskell/vty/openSUSE_Leap_42.2/x86_64

**Comment by hramrach** [comment]
how has this change no meaning?

The package does not build without

@@ -125,6 +125,8 @@
%files -f %{name}.files
%defattr(-,root,root,-)
%doc LICENSE
+%docdir /usr/share/%{pkg_name}-%{version}
+/usr/share/%{pkg_name}-%{version}

**Comment by peti** [comment]
When I run `cabal-rpm spec vty` on openSUSE Tumbleweed, it generates:

~~~
[...]
%files -f %{name}.files
%defattr(-,root,root,-)
%doc LICENSE
%{_bindir}/vty-demo
%{_bindir}/vty-mode-demo
%{_datadir}/%{pkg_name}-%{version}


%files devel -f %{name}-devel.files
%defattr(-,root,root,-)
%doc AUTHORS CHANGELOG README.md TODO
[...]
~~~

**Comment by hramrach** [comment]
Then it was fixed in the meantime or I genenerated this on a Leap machine. It's been a few weeks already.

**Comment by peti** [comment]
If you're using `cabal-rpm` from Factory, then you're using the same version I used.

You might want to try running the tool with the flag "--distro=SUSE", to make sure it doesn't misdetect the platform it's running on, but I don't think that's the issue here.

**Comment by hramrach** [comment]
It works on Tumbleweed and Leap 42.2 now so it's fixed.
