### ISSUE TITLE
cabal-rpm should package data

### ISSUE THREAD

**Issue by hramrach** [juhp/cabal-rpm#48]
Hello,

I have been hit by issue #47 once more so I  looked more into it and the problem is this:

The vty cabal package adds (incorrectly) documentation as data, and cagal-rpm (incorrectly) ignores data and does not package it in the rpm spec resulting in build error.

--- vty-5.15/vty.cabal~	2017-01-24 20:46:18.000000000 +0100
+++ vty-5.15/vty.cabal	2017-02-06 14:01:40.771392638 +0100
@@ -26,7 +26,7 @@
   &#169; Jonathan Daugherty; BSD3 license.
 cabal-version:       >= 1.18
 build-type:          Simple
-data-files:          README.md,
+extra-doc-files:     README.md,
                      AUTHORS,
                      CHANGELOG.md,
                      LICENSE

**Comment by juhp** [comment]
Could you post some output?

**Comment by juhp** [comment]
I just tried on Fedora and vty built okay for me.

**Comment by juhp** [comment]
Maybe you want to try with my latest release or git?

Otherwise you could report the bug against the opensuse's fork.

**Comment by peti** [comment]
Just FYI: we no longer maintain a fork for openSUSE. We ship the pristine cabal-rpm version -- unpatched.

**Comment by hramrach** [comment]
The error is that files specified as data-files in cabal file are not installed in rpm spec file (ie not specified in the %files section).

I can easily test with the cabal-rpm version in opensuse but I am not set up for building cabal-rpm from source atm.

issue #47 has some details about the changes I needed to build a package that distributes documentation as data-files (which is wrong but should not fail the build nonetheless).

**Comment by juhp** [comment]
Is this still a problem?

**Comment by hramrach** [comment]
Seems data files are installed when

(hasExecPkg && not selfdep) || (hasLib && (selfdep  || not binlib))

not sure if that leaves some cases out.

The vty package that was broken originally is now fixed but you can re-break it by reverting the patch in the issue description to get a testcase.

**Comment by juhp** [comment]
@hramrach I think it should be, though I admit it is not trivial evident.

Please reopen if you should find any more problems.
