### ISSUE TITLE
`cabal-rpm install` fails if ghc-rpm-macros is missing

### ISSUE THREAD

**Issue by dashea** [juhp/cabal-rpm#49]
The command it tried to exec ends up being ["dnf", "", "install", "ghc-rpm-macros"], which causes dnf to print the help output and exit.

**Comment by dashea** [comment]
Actually this seems to be any time cabal-rpm tries to install a dependency that's available via dnf. This is using cabal-rpm-0.11.1-1.fc26.x86_64

**Comment by juhp** [comment]
I can't reproduce this yet. I works for me.

**Comment by juhp** [comment]
Just to be sure what is the output of `cabal-rpm --version`?

**Comment by juhp** [comment]
Is because you are not using sudo perhaps?

**Comment by juhp** [comment]
Also could you post the output from cabal-rpm when you do this?

**Comment by juhp** [comment]
Nevermind, I think I have fixed this now in git.

Perhaps you could just test it works for you or I can do a release on Hackage that you can `cabal install` if that is easier for you.

**Comment by dashea** [comment]
The latest from git works for me, thanks

**Comment by juhp** [comment]
Great thanks

**Comment by juhp** [comment]
This should be fixed in cabal-rpm-0.11.2
