### ISSUE TITLE
Left-over file under /usr/share/licenses/<package>/LICENSE breaks rpmbuild

### ISSUE THREAD

**Issue by atodorov** [juhp/cabal-rpm#56]
According to this log:
https://copr-be.cloud.fedoraproject.org/results/@weldr/bdcs/fedora-27-x86_64/00728213-bdcs/build.log.gz

```
BUILDSTDERR:     Installed (but unpackaged) file(s) found:
BUILDSTDERR:    /usr/share/licenses/bdcs/LICENSE
```
Here's my copr build:
https://copr.fedorainfracloud.org/coprs/g/weldr/bdcs/build/728213/

and the dist git log:
http://copr-dist-git.fedorainfracloud.org/cgit/@weldr/bdcs/bdcs.git/commit/?id=92bf206711747b7286033779731f3dac6a7287a6

I see a changelog entry `- put license files in lib subpackage` but nothing else related to this. Are we supposed to somehow modify the existing Haskell package or not ?

**Comment by juhp** [comment]
Can you attach `cabal-rpm diff` output?

**Comment by juhp** [comment]
Okay I had a quick look at Hackage and the spec file.
I think bdcs is linked to ghc-bdcs, right?  In which case I let ghc-bdcs carry the LICENSE file.
I think `cabal-rpm` tries to move the LICENSE file into `/usr/share/licenses/ghc-bdcs/LICENSE`.
Does that help at all?  I know it is a bit tedious, but this seems the most reasonable thing to do other than duplicating the license file.

**Comment by atodorov** [comment]
@juhp I think this was a problem on our end so closing for now.
