### ISSUE TITLE
cabal-rpm.1.md: SYNOPSIS is a single paragraph, a subject to reflow

### ISSUE THREAD

**Issue by van-de-bugger** [juhp/cabal-rpm#58]
This file is a markdown source. What the tool should be used to generate man page?

In case of `pandoc` there is a bug in SYNOPSIS section. The source code looks like:

    # SYNOPSIS
    cabal-rpm [*options*] spec [*path-or-pkg*]
    cabal-rpm [*options*] local [*path-or-pkg*]
    cabal-rpm [*options*] srpm [*path-or-pkg*]
    ...

All these command lines look ok in markdown, but this is a _single paragraph_, a _subject to reflow_. Being processed by `pandoc` and `man` (`groff`), it will look like

    SYNOPSIS
        cabal-rpm   [options]  spec  [path-or-pkg]  cabal-rpm  [options]  local
        [path-or-pkg] cabal-rpm [options]  srpm  [path-or-pkg]  cabal-rpm  [op-
        tions]  prep  [path-or-pkg]  cabal-rpm [options] builddep [path-or-pkg]
        cabal-rpm [options] install [path-or-pkg] cabal-rpm  [options]  depends
        [path-or-pkg] cabal-rpm [options] requires [path-or-pkg] cabal-rpm [op-
        tions] missingdeps [path-or-pkg] cabal-rpm [options] diff [path-or-pkg]
        cabal-rpm  [options]  update  [path-or-pkg] cabal-rpm [options] refresh
        [path-or-pkg]

Hard linebreaks must be used to avoid such mess:

    # SYNOPSIS
    cabal-rpm [*options*] spec [*path-or-pkg*] \
    cabal-rpm [*options*] local [*path-or-pkg*] \
    ...
    cabal-rpm [*options*] update [*path-or-pkg*] \
    cabal-rpm [*options*] refresh [*path-or-pkg*]

The last line should not have linebreak.

**Comment by juhp** [comment]
Thank you very much for reporting this.
