### ISSUE TITLE
Crash on fromJust if no library is specified

### ISSUE THREAD

**Issue by dminuoso** [juhp/cabal-rpm#61]
If the project uses no library (or a sub-library instead of a library), the code crashes with 

`cabal-rpm: Maybe.fromJust: Nothing`

triggered by https://github.com/juhp/cabal-rpm/blob/master/src/Commands/Spec.hs#L344

I'm not intimately familiar with the internals, so I can't say what the right cause of action is. Either the README.md should document that a `library`is mandatory, or it should consult sub libraries as well. Why does this need a library at all?

**Comment by juhp** [comment]
Thanks for reporting this.
It would help me to have more details or an example of how to reproduce this.
Does commit 1c7760c help?

I think current support for internal libraries is incomplete: they get listed as package dependencies - I will try to improve that later.

**Comment by juhp** [comment]
Going to close this, assuming it is okay now.
But if not please comment or (re)open issue, thanks
