### ISSUE TITLE
Support rpmautospec

### ISSUE THREAD

**Issue by QuLogic** [juhp/cabal-rpm#66]
If a spec is using rpmautospec (`%autorelease` and `%autochangelog`), then this will be ignored and `cabal-rpm update` will reset `Release` to 1 and add an entry to the `%changelog`.

In this case, neither change should happen as the changelog will transfer from the commit message (which `cabal-rpm` already creates).

**Comment by juhp** [comment]
Thanks for reporting.
So ya currently in git the only thing that works is `cblrpm spec` which does preserve the autospec macros.
I will try to release that first probably, but I will try to get to this bug before too long.

**Comment by juhp** [comment]
This should work better now in 2.0.11, which I released yesterday.
But do say if you still see problems.
